/**
 * VocalMirror — Acoustic Constants, Limits, Presets and Defaults
 */

import {
  DSPParameters,
  ParameterLimits,
  PhysiologicalPresetKey,
  PhysiologicalPreset,
  CompressorConfig,
} from '../types/audio';

export const DEFAULT_DSP_PARAMS: DSPParameters = {
  lowShelfFreq: 180,
  lowShelfGain: 8.0,
  mandibleResFreq: 240,
  mandibleResGain: 4.5,
  mandibleResQ: 1.8,
  sinusResFreq: 780,
  sinusResGain: 3.0,
  sinusResQ: 2.2,
  antiResFreq: 1650,
  antiResGain: -3.5,
  antiResQ: 2.0,
  tissueCutoffFreq: 4000,
  tissueCutoffQ: 0.707,
  highShelfFreq: 5500,
  highShelfGain: -6.0,
  masterGain: 0.0,
};

export const PARAMETER_LIMITS: ParameterLimits = {
  lowShelfFreq: {
    min: 80,
    max: 300,
    step: 5,
    default: 180,
    unit: 'Hz',
    label: 'Chest Resonance Freq',
    description: 'Fundamental chest and laryngeal bone conduction frequency band.',
    group: 'chest_bone',
  },
  lowShelfGain: {
    min: 0,
    max: 14,
    step: 0.5,
    default: 8.0,
    unit: 'dB',
    label: 'Chest Bass Boost',
    description: 'Amplification of low-frequency vibrations conducted via chest and neck cartilage.',
    group: 'chest_bone',
  },
  mandibleResFreq: {
    min: 150,
    max: 400,
    step: 5,
    default: 240,
    unit: 'Hz',
    label: 'Mandible Jaw Freq',
    description: 'Mandibular osseous vibration resonance center frequency.',
    group: 'chest_bone',
  },
  mandibleResGain: {
    min: 0,
    max: 8,
    step: 0.5,
    default: 4.5,
    unit: 'dB',
    label: 'Mandible Jaw Gain',
    description: 'Peak resonance boost from jawbone acoustic coupling into the ear canal.',
    group: 'chest_bone',
  },
  mandibleResQ: {
    min: 0.5,
    max: 4.0,
    step: 0.1,
    default: 1.8,
    unit: 'Q',
    label: 'Mandible Jaw Q',
    description: 'Sharpness/bandwidth of the mandibular bone resonance peak.',
    group: 'chest_bone',
  },
  sinusResFreq: {
    min: 500,
    max: 1200,
    step: 10,
    default: 780,
    unit: 'Hz',
    label: 'Sinus Cavity Freq',
    description: 'Maxillary and frontal cranial sinus cavity resonance frequency.',
    group: 'cavity_resonance',
  },
  sinusResGain: {
    min: 0,
    max: 6,
    step: 0.5,
    default: 3.0,
    unit: 'dB',
    label: 'Sinus Cavity Gain',
    description: 'Harmonic boost caused by acoustic resonance in facial cranial cavities.',
    group: 'cavity_resonance',
  },
  sinusResQ: {
    min: 0.5,
    max: 5.0,
    step: 0.1,
    default: 2.2,
    unit: 'Q',
    label: 'Sinus Cavity Q',
    description: 'Bandwidth of the sinus cavity harmonic formant.',
    group: 'cavity_resonance',
  },
  antiResFreq: {
    min: 1200,
    max: 2500,
    step: 25,
    default: 1650,
    unit: 'Hz',
    label: 'Anti-Resonance Notch Freq',
    description: 'Nasopharyngeal acoustic interference frequency causing natural vocal attenuation.',
    group: 'cavity_resonance',
  },
  antiResGain: {
    min: -8,
    max: 0,
    step: 0.5,
    default: -3.5,
    unit: 'dB',
    label: 'Anti-Resonance Notch Depth',
    description: 'Depth of acoustic cancellation within internal cranial pathways.',
    group: 'cavity_resonance',
  },
  antiResQ: {
    min: 0.5,
    max: 4.0,
    step: 0.1,
    default: 2.0,
    unit: 'Q',
    label: 'Anti-Resonance Q',
    description: 'Selectivity of the cranial antiresonance notch.',
    group: 'cavity_resonance',
  },
  tissueCutoffFreq: {
    min: 2000,
    max: 6000,
    step: 50,
    default: 4000,
    unit: 'Hz',
    label: 'Tissue Damping Cutoff',
    description: 'Upper frequency boundary where viscoelastic skull tissues absorb sound vibrations.',
    group: 'tissue_damping',
  },
  tissueCutoffQ: {
    min: 0.5,
    max: 1.5,
    step: 0.05,
    default: 0.707,
    unit: 'Q',
    label: 'Tissue Rolloff Q',
    description: 'Damping curve sharpness (0.707 = maximally flat Butterworth rolloff).',
    group: 'tissue_damping',
  },
  highShelfFreq: {
    min: 4000,
    max: 8000,
    step: 100,
    default: 5500,
    unit: 'Hz',
    label: 'Air Sibilance Shelf Freq',
    description: 'High-frequency sibilance softening shelf frequency.',
    group: 'tissue_damping',
  },
  highShelfGain: {
    min: -14,
    max: 0,
    step: 0.5,
    default: -6.0,
    unit: 'dB',
    label: 'Air Sibilance Damping',
    description: "High-frequency attenuation reducing harsh sibilants ('s', 'sh', 'f') internally.",
    group: 'tissue_damping',
  },
  masterGain: {
    min: -6,
    max: 6,
    step: 0.5,
    default: 0.0,
    unit: 'dB',
    label: 'Master Trim',
    description: 'Overall output volume trimming level.',
    group: 'master',
  },
};

export const ACOUSTIC_PRESETS: Record<PhysiologicalPresetKey, PhysiologicalPreset> = {
  natural_standard: {
    id: 'natural_standard',
    name: 'Standard Biological (Adult)',
    tag: 'Balanced',
    description: 'Standard adult cranial acoustic profile with balanced +8dB chest warmth and 4kHz tissue rolloff.',
    params: {
      lowShelfFreq: 180,
      lowShelfGain: 8.0,
      mandibleResFreq: 240,
      mandibleResGain: 4.5,
      mandibleResQ: 1.8,
      sinusResFreq: 780,
      sinusResGain: 3.0,
      sinusResQ: 2.2,
      antiResFreq: 1650,
      antiResGain: -3.5,
      antiResQ: 2.0,
      tissueCutoffFreq: 4000,
      tissueCutoffQ: 0.707,
      highShelfFreq: 5500,
      highShelfGain: -6.0,
      masterGain: 0.0,
    },
  },
  deep_chest_male: {
    id: 'deep_chest_male',
    name: 'Deep Chest & Heavy Mandible',
    tag: 'Warm / Bass',
    description: 'Baritone/bass vocal resonance featuring heavy 140Hz fundamental boost and pronounced skull tissue absorption.',
    params: {
      lowShelfFreq: 140,
      lowShelfGain: 11.0,
      mandibleResFreq: 200,
      mandibleResGain: 6.0,
      mandibleResQ: 2.0,
      sinusResFreq: 700,
      sinusResGain: 3.5,
      sinusResQ: 2.5,
      antiResFreq: 1500,
      antiResGain: -4.5,
      antiResQ: 2.2,
      tissueCutoffFreq: 3400,
      tissueCutoffQ: 0.707,
      highShelfFreq: 5000,
      highShelfGain: -8.0,
      masterGain: -1.0,
    },
  },
  bright_cranial_female: {
    id: 'bright_cranial_female',
    name: 'Bright Cranial / High Formant',
    tag: 'Clarity / Soprano',
    description: 'Higher fundamental resonance at 220Hz with prominent sinus cavity response and gentle high-frequency damping.',
    params: {
      lowShelfFreq: 220,
      lowShelfGain: 6.5,
      mandibleResFreq: 310,
      mandibleResGain: 4.0,
      mandibleResQ: 1.6,
      sinusResFreq: 920,
      sinusResGain: 4.5,
      sinusResQ: 2.0,
      antiResFreq: 1800,
      antiResGain: -2.5,
      antiResQ: 1.8,
      tissueCutoffFreq: 4800,
      tissueCutoffQ: 0.707,
      highShelfFreq: 6500,
      highShelfGain: -4.0,
      masterGain: 0.5,
    },
  },
  intense_confrontation: {
    id: 'intense_confrontation',
    name: 'Maximum Voice Confrontation',
    tag: 'High Contrast',
    description: 'Maximum contrast profile highlighting the psychological gap between recorded air sound and internal perception.',
    params: {
      lowShelfFreq: 160,
      lowShelfGain: 13.0,
      mandibleResFreq: 220,
      mandibleResGain: 7.0,
      mandibleResQ: 2.4,
      sinusResFreq: 850,
      sinusResGain: 5.0,
      sinusResQ: 2.8,
      antiResFreq: 1700,
      antiResGain: -6.0,
      antiResQ: 2.5,
      tissueCutoffFreq: 3200,
      tissueCutoffQ: 0.8,
      highShelfFreq: 4800,
      highShelfGain: -10.0,
      masterGain: -1.5,
    },
  },
};

export const DEFAULT_COMPRESSOR_SETTINGS: CompressorConfig = {
  threshold: -3.0,  // dBFS
  knee: 4.0,        // dB
  ratio: 12.0,      // 12:1 limiting ratio
  attack: 0.002,    // 2ms ultra-fast transient catch
  release: 0.040,   // 40ms transparent bass recovery
};

export const AUDIO_CONSTANTS = {
  CROSSFADE_DURATION_SEC: 0.025, // 25ms equal-power linear crossfade duration
  PARAM_SMOOTHING_TIME_SEC: 0.015, // 15ms AudioParam setTargetAtTime time constant for zipper noise elimination
  DEFAULT_FFT_SIZE: 2048,
  MIN_DECIBELS: -100,
  MAX_DECIBELS: -30,
  SMOOTHING_TIME_CONSTANT: 0.8,
  INVERSE_SUBSONIC_HIGHPASS_FREQ: 45, // Hz
  INVERSE_SUBSONIC_HIGHPASS_Q: 0.707,
  INVERSE_HIGHSHELF_AIR_FREQ: 3500, // Hz
  INVERSE_MAX_AIR_BOOST_DB: 8.0, // Maximum safe high-shelf boost in inverse mode
  DYNAMIC_HEADROOM_MIN_ATTEN_DB: 3.0,
  DYNAMIC_HEADROOM_MAX_ATTEN_DB: 12.0,
  DYNAMIC_HEADROOM_SCALE_FACTOR: 0.75,
} as const;
